### ISSUE TITLE
2 SPI devices

### ISSUE THREAD

**Issue by Adrianotiger** [ZoetropeLabs/AS5048A-Arduino#1]
Hi,
I have 2 AS5047 devices and want to set both with the SPI (with 2 different chip select pins).
This library doesn't work correctly, because the SPI is initialised again on each device.

**SPISettings** and **SPI.beginTransaction** should be used when you have more than 1 SPI device.

So, on each transfer, you can select the right cs and you will be able to use more than only 1 SPI device.

**Comment by benhowes** [comment]
Hi! It looks like you should be able to add `SPI.beginTransaction()` and `SPI.endTransaction()` in the  `AS5048A::read` and `AS5048A::write` functions, along with setting the SS in the settings as you mention.

If you get this working in a fork, I'd love to have a pull request to merge in :)

https://www.arduino.cc/en/Reference/SPI

**Comment by Adrianotiger** [comment]
Hi Ben.
I made a pull request. I am new to github and still need to learn how to do some changes on the code. Hope I made it correctly.

**Comment by benhowes** [comment]
Closed by #2
