### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by eborghi10** [ZoetropeLabs/AS5048A-Arduino#4]
Hi, I used your library with an Arduino Mega2560 and I can share [my example](https://github.com/eborghi10/AS5048A-Arduino-Example) program with you my example to help other people.

Best regards. Emiliano.

**Comment by benhowes** [comment]
Hi @eborghi10 it looks like you could use the `getRotation` rather than `getRawRotation` so that you don't need to do the normalisation in your own code? 

Did you re-implement it because something wasn't working?

Thanks

**Comment by eborghi10** [comment]
When I tested the example code, the function `getRotation()` didn't work because some range of angles were not being displayed correctly. For example, I can see the angles from 270° to 45°.
So, to avoid modificating the library I decided to make the example using `getRawRotation()` because it was giving me good results (register values from 0h to 3FFFh).
